OBJS = ast.cmo parser.cmo scanner.cmo compile.cmo hollabach.cmo 
#execute.cmo hollabach.cmo
#interpret.cmo bytecode.cmo

TESTS = \
arith1 \
arith2 \
fib \
for1 \
func1 \
func2 \
func3 \
gcd \
global1 \
hello \
if1 \
if2 \
if3 \
if4 \
ops1 \
var1 \
while1

TARFILES = Makefile testall.sh scanner.mll parser.mly \
	ast.ml compile.ml hollbach.ml \
	$(TESTS:%=tests/test-%.mc) \
	$(TESTS:%=tests/test-%.out)
#interpret.ml execute.ml bytecode.ml
hollabach : $(OBJS)
	ocamlc -g -o hollabach $(OBJS)

.PHONY : test
test : hollabach testall.sh
	./testall.sh

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -g -c $<

%.cmi : %.mli
	ocamlc -g -c $<

hollabach.tar.gz : $(TARFILES)
	cd .. && tar czf hollabach/hollabach.tar.gz $(TARFILES:%=hollabach/%)

compile:
	./hollabach -c out.holla < testprog.bach; cd CSV2MIDI; java CSV2MIDI ../out.holla testingnew.midi
.PHONY : clean
clean :
	rm -f hollabach parser.ml parser.mli scanner.ml testall.log \
	*.cmo *.cmi *.out *.diff

# Generated by ocamldep *.ml *.mli
ast.cmo: 
ast.cmx: 
#bytecode.cmo: ast.cmo 
#bytecode.cmx: ast.cmx 
compile.cmo: bytecode.cmo ast.cmo 
compile.cmx: bytecode.cmx ast.cmx 
#execute.cmo: bytecode.cmo ast.cmo 
#execute.cmx: bytecode.cmx ast.cmx 
#interpret.cmo: ast.cmo 
#interpret.cmx: ast.cmx 
hollabach.cmo: scanner.cmo parser.cmi compile.cmo ast.cmo
hollabach.cmx: scanner.cmx parser.cmx compile.cmx ast.cmx
parser.cmo: ast.cmo parser.cmi 
parser.cmx: ast.cmx parser.cmi 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 
parser.cmi: ast.cmo 
